-- Wishlist Items Migration V2
-- Run this in your Supabase SQL Editor to add wishlist functionality
-- This version includes AI-generated tracking and category support

-- Wishlist Items table (for saving desired clothing items)
create table if not exists wishlist_items (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references auth.users,
  
  -- Product information
  name text not null,
  brand text,
  price text not null,
  currency text default 'USD',
  image text not null,
  url text not null,
  retailer text not null,
  notes text default '',
  original_price text,
  discount text,
  
  -- Organization
  category text,
  subcategory text,
  
  -- AI-generated tracking
  ai_generated boolean default false,
  design_prompt text,
  ai_generated_image text,
  
  -- Timestamps
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Wishlist items indexes for better query performance
create index if not exists wishlist_items_user_id_idx on wishlist_items(user_id);
create index if not exists wishlist_items_created_at_idx on wishlist_items(created_at desc);
create index if not exists wishlist_items_brand_idx on wishlist_items(brand);
create index if not exists wishlist_items_retailer_idx on wishlist_items(retailer);
create index if not exists wishlist_items_category_idx on wishlist_items(category);
create index if not exists wishlist_items_ai_generated_idx on wishlist_items(ai_generated);

-- Wishlist items RLS (Row Level Security) policies
alter table wishlist_items enable row level security;

create policy "Users can view own wishlist items" on wishlist_items
  for select using (auth.uid() = user_id);

create policy "Users can insert own wishlist items" on wishlist_items
  for insert with check (auth.uid() = user_id);

create policy "Users can update own wishlist items" on wishlist_items
  for update using (auth.uid() = user_id);

create policy "Users can delete own wishlist items" on wishlist_items
  for delete using (auth.uid() = user_id);

-- Function to automatically update updated_at timestamp
create or replace function update_wishlist_items_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- Trigger to auto-update updated_at on row update
drop trigger if exists update_wishlist_items_updated_at_trigger on wishlist_items;
create trigger update_wishlist_items_updated_at_trigger
  before update on wishlist_items
  for each row
  execute function update_wishlist_items_updated_at();

-- Comments for documentation
comment on table wishlist_items is 'Stores user wishlist items for shopping with AI-generated tracking';
comment on column wishlist_items.user_id is 'User ID from auth.users';
comment on column wishlist_items.name is 'Product name';
comment on column wishlist_items.brand is 'Brand name';
comment on column wishlist_items.price is 'Current price with currency symbol (e.g., "$65")';
comment on column wishlist_items.currency is 'Currency code (e.g., "USD", "GBP")';
comment on column wishlist_items.image is 'Product image URL';
comment on column wishlist_items.url is 'Product page URL';
comment on column wishlist_items.retailer is 'Retailer/store name';
comment on column wishlist_items.notes is 'User notes about the item';
comment on column wishlist_items.original_price is 'Original price before discount (optional)';
comment on column wishlist_items.discount is 'Discount text (e.g., "30% OFF")';
comment on column wishlist_items.category is 'Fashion category (e.g., "Tops", "Shoes")';
comment on column wishlist_items.subcategory is 'Fashion subcategory (e.g., "T-Shirts", "Sneakers")';
comment on column wishlist_items.ai_generated is 'Whether item was generated by AI Design Shop';
comment on column wishlist_items.design_prompt is 'Original AI design prompt used';
comment on column wishlist_items.ai_generated_image is 'URL to AI-generated reference image';
