-- ============================================
-- Weekly Challenges Table
-- ============================================
-- Stores weekly fashion challenges for users
-- Generated each Monday, tracked with Claude AI
-- ============================================

CREATE TABLE IF NOT EXISTS weekly_challenges (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  week_start DATE NOT NULL,
  challenge_type TEXT NOT NULL,
  challenge_text TEXT NOT NULL,
  accepted_at TIMESTAMP,
  completed_at TIMESTAMP,
  completion_data JSONB,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  
  -- Ensure one challenge per user per week
  UNIQUE(user_id, week_start)
);

-- ============================================
-- Indexes
-- ============================================

CREATE INDEX IF NOT EXISTS idx_weekly_challenges_user 
  ON weekly_challenges(user_id);

CREATE INDEX IF NOT EXISTS idx_weekly_challenges_week 
  ON weekly_challenges(week_start);

CREATE INDEX IF NOT EXISTS idx_weekly_challenges_user_week 
  ON weekly_challenges(user_id, week_start);

CREATE INDEX IF NOT EXISTS idx_weekly_challenges_accepted 
  ON weekly_challenges(user_id, accepted_at) 
  WHERE accepted_at IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_weekly_challenges_completed 
  ON weekly_challenges(user_id, completed_at) 
  WHERE completed_at IS NOT NULL;

-- ============================================
-- Row Level Security (RLS)
-- ============================================

ALTER TABLE weekly_challenges ENABLE ROW LEVEL SECURITY;

-- Users can only see their own challenges
CREATE POLICY "Users can view own challenges"
  ON weekly_challenges
  FOR SELECT
  USING (auth.uid() = user_id);

-- Users can insert their own challenges
CREATE POLICY "Users can insert own challenges"
  ON weekly_challenges
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Users can update their own challenges
CREATE POLICY "Users can update own challenges"
  ON weekly_challenges
  FOR UPDATE
  USING (auth.uid() = user_id);

-- Users can delete their own challenges
CREATE POLICY "Users can delete own challenges"
  ON weekly_challenges
  FOR DELETE
  USING (auth.uid() = user_id);

-- ============================================
-- Comments
-- ============================================

COMMENT ON TABLE weekly_challenges IS 'Stores weekly fashion challenges generated by Claude AI';
COMMENT ON COLUMN weekly_challenges.challenge_type IS 'Type of challenge: wear_color, try_new_combo, closet_hero, monochrome, pattern_mix, accessory_focus, seasonal_twist, color_block';
COMMENT ON COLUMN weekly_challenges.challenge_text IS 'User-friendly challenge description (max 60 chars)';
COMMENT ON COLUMN weekly_challenges.accepted_at IS 'When user accepted the challenge';
COMMENT ON COLUMN weekly_challenges.completed_at IS 'When challenge was completed';
COMMENT ON COLUMN weekly_challenges.completion_data IS 'JSON with outfit_ids and compliment_text from Claude';
